# K-Nearest Neighbors Algorithm example - 1 

KNN as Classifier

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [12]:
dataset = pd.read_csv("D:\Data Science\Dataset\iris.csv")
dataset = dataset.rename(columns= {'sepal_length':'sepal-length', 'sepal_width' : 'sepal-width' ,'petal_length':'petal-length', 'petal_width': 'petal-width','species':'Class'})
dataset.head()

sepal-length  sepal-width  petal-length  petal-width   Class
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [15]:
# Data Preprocessing will be done with the help of following script lines.
# Splitting the dataset into independent (x) and dependent (y) variables

x = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 4].values

In [32]:
# Next, we will divide the data into train and test split. Following code will split the dataset into 60% training data
#and 40% of testing data 

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.40)

# print('length of x_train : ',len(x_train), '\nlength of x_test : ',len(x_test))
# print('length of y_train : ',len(y_train), '\nlength of y_test : ',len(y_test))

length of x_train :  90 
length of x_test :  60
length of y_train :  90 
length of y_test :  60


In [39]:
# Next, data scaling will be done as follows −

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)


In [41]:
# Next, train the model with the help of KNeighborsClassifier class of sklearn as follows −

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=8, p=2,
           weights='uniform')

In [44]:
# At last we need to make prediction. It can be done with the help of following script −

y_pred = classifier.predict(x_test)


In [45]:
# Next, print the results as follows −

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[19  0  0]
 [ 0 23  2]
 [ 0  1 15]]
Classification Report:
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        19
 versicolor       0.96      0.92      0.94        25
  virginica       0.88      0.94      0.91        16

avg / total       0.95      0.95      0.95        60

Accuracy: 0.95


# KNN as Regressor

In [49]:
dataset
array = dataset.values
X = array[:,:2]
Y = array[:,2]
dataset.shape
# print(X)
# print(Y)

[[5.1 3.5]
 [4.9 3.0]
 [4.7 3.2]
 [4.6 3.1]
 [5.0 3.6]
 [5.4 3.9]
 [4.6 3.4]
 [5.0 3.4]
 [4.4 2.9]
 [4.9 3.1]
 [5.4 3.7]
 [4.8 3.4]
 [4.8 3.0]
 [4.3 3.0]
 [5.8 4.0]
 [5.7 4.4]
 [5.4 3.9]
 [5.1 3.5]
 [5.7 3.8]
 [5.1 3.8]
 [5.4 3.4]
 [5.1 3.7]
 [4.6 3.6]
 [5.1 3.3]
 [4.8 3.4]
 [5.0 3.0]
 [5.0 3.4]
 [5.2 3.5]
 [5.2 3.4]
 [4.7 3.2]
 [4.8 3.1]
 [5.4 3.4]
 [5.2 4.1]
 [5.5 4.2]
 [4.9 3.1]
 [5.0 3.2]
 [5.5 3.5]
 [4.9 3.1]
 [4.4 3.0]
 [5.1 3.4]
 [5.0 3.5]
 [4.5 2.3]
 [4.4 3.2]
 [5.0 3.5]
 [5.1 3.8]
 [4.8 3.0]
 [5.1 3.8]
 [4.6 3.2]
 [5.3 3.7]
 [5.0 3.3]
 [7.0 3.2]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [4.9 2.4]
 [6.6 2.9]
 [5.2 2.7]
 [5.0 2.0]
 [5.9 3.0]
 [6.0 2.2]
 [6.1 2.9]
 [5.6 2.9]
 [6.7 3.1]
 [5.6 3.0]
 [5.8 2.7]
 [6.2 2.2]
 [5.6 2.5]
 [5.9 3.2]
 [6.1 2.8]
 [6.3 2.5]
 [6.1 2.8]
 [6.4 2.9]
 [6.6 3.0]
 [6.8 2.8]
 [6.7 3.0]
 [6.0 2.9]
 [5.7 2.6]
 [5.5 2.4]
 [5.5 2.4]
 [5.8 2.7]
 [6.0 2.7]
 [5.4 3.0]
 [6.0 3.4]
 [6.7 3.1]
 [6.3 2.3]
 [5.6 3.0]
 [5.5 2.5]
 [5.5 2.6]

In [55]:
# Next, import KNeighborsRegressor from sklearn to fit the model −

from sklearn.neighbors import KNeighborsRegressor
knnr = KNeighborsRegressor(n_neighbors = 10)
knnr.fit(X, y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=10, p=2,
          weights='uniform')

In [57]:
# At last, we can find the MSE as follows −

print ("The MSE is:", format(np.power(y-knnr.predict(X),2).mean()))


# output : The MSE is: 0.12226666666666669

TypeError: unsupported operand type(s) for /: 'str' and 'int'